limit generated messages to prevent M_TOO_LARGE
Sorunome/mx-puppet-bridge pull request #10
Opened 2019-09-26 07:43 UTC by twouters

Just a proposal to fix #8 

I didn't want to limit all messages because it's:
- too hard to properly split a string without breaking markdown or html elements
- probably impossible to keep track of puppeted event id's

Instead I've decided that it's probably better to only limit the size of self-generated messages
It's just an idea. If there's a better way to do this, feel free to comment.

2019-09-26 07:49 UTC, twouters commented
Oh, right, `maxMsgSize` is just sort of an arbitrary number (it's what Slack defines as maximum size for messages in input field)

2019-09-27 16:11 UTC, Sorunome requested changes
Looks good, just one small nitpicking!

2019-09-27 16:11 UTC, Sorunome commented on src/botprovisioner.ts
> +		const maxMsgSize = 4000;
can you maybe make this a global constant on top in all caps? Like, outside the class `const MAX_MSG_SIZE = 4000;`

2019-09-28 11:00 UTC, Sorunome approved these changes

2019-09-28 11:01 UTC, Sorunome commented
Thanks a lot!

2019-09-28 11:02 UTC, merged